# Generated by Django 5.2.5 on 2026-03-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(verbose_name='Yaş')),
                ('blood_pressure', models.CharField(max_length=15, verbose_name='Tansiyon (Örn: 12.8)')),
                ('sugar_level', models.FloatField(verbose_name='Şeker Seviyesi')),
                ('risk_score', models.CharField(blank=True, max_length=50, verbose_name='Risk Skoru')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ölçüm Tarihi')),
            ],
            options={
                'verbose_name': 'Sağlık Kaydı',
                'verbose_name_plural': 'Sağlık Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
