# Generated by Django 5.2.5 on 2026-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Proje Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('status', models.CharField(choices=[('Devam Ediyor', 'Devam Ediyor'), ('Tamamlandı', 'Tamamlandı')], default='Devam Ediyor', max_length=20, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
