# Generated by Django 5.2.5 on 2026-04-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kapsamlı Sağlık Kaydı', 'verbose_name_plural': 'Kapsamlı Sağlık Kayıtları'},
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='activity_level',
            field=models.CharField(choices=[('LOW', 'Hareketsiz'), ('MEDIUM', 'Orta Derece Aktif'), ('HIGH', 'Çok Aktif')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='bmi',
            field=models.FloatField(blank=True, null=True, verbose_name='VKE (BMI)'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='height',
            field=models.FloatField(default=170, verbose_name='Boy (cm)'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='is_smoking',
            field=models.CharField(choices=[('YES', 'Evet'), ('NO', 'Hayır')], default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='weight',
            field=models.FloatField(default=70, verbose_name='Kilo (kg)'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='risk_score',
            field=models.CharField(blank=True, max_length=100, verbose_name='Risk Analiz Skoru'),
        ),
    ]
