# Generated by Django 5.2.5 on 2026-04-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_healthrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='patient_name',
            field=models.CharField(default='İsimsiz Hasta', max_length=100, verbose_name='Hasta Adı'),
        ),
    ]
